"""Create ForecastsHeader table

Revision ID: e872f5ca2b13
Revises: 9fa350a848ec
Create Date: 2024-12-07 16:44:32.347234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e872f5ca2b13'
down_revision: Union[str, None] = '9fa350a848ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
